# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-11 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('passWord', models.CharField(max_length=50)),
                ('userType', models.CharField(max_length=10)),
            ],
        ),
    ]
